version: '3'

services:
  database:
    image: postgres:alpine
    # container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017


# docker run --name mongobarber -p 27017:27017 -d -t mongo
